In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../results/metrics/se_auroc_summary.csv")
df

,model,n_questions,M,auroc,accuracy,avg_entropy,std_entropy,total_time_s,nli_calls_total,load_time_s,model_size_mb,ram_after_load_mb,ram_available_mb
0,TinyLlama/TinyLlama-1.1B-Chat-v1.0,100,10,0.6608,0.29,2.1019,0.4331,9173.6,9000,7.266,4196.4,719.8,514.8
1,microsoft/phi-1_5,100,10,0.4944,0.11,2.3012,0.0138,32455.6,9000,8.721,5410.3,3375.6,1959.2
2,Qwen/Qwen1.5-1.8B-Chat,100,10,0.5676,0.19,2.2241,0.2215,44840.6,9000,8.583,7006.9,5292.7,3136.8

In [8]:
df_base = pd.read_csv("../results/metrics/baseline_metrics.csv")
df_base

,model,M,device,load_time_s,model_size_mb,ram_after_load_mb,ram_available_mb,gen_time_s,total_new_tokens,tokens_per_sec,avg_tokens_per_sample,avg_time_per_sample_s
0,TinyLlama/TinyLlama-1.1B-Chat-v1.0,10,cpu,6.297,4196.4,2174.1,1636.0,191.105,1000,5.23,100.0,19.111
1,microsoft/phi-1_5,10,cpu,9.051,5410.3,1462.3,1637.7,224.072,1000,4.46,100.0,22.407
2,Qwen/Qwen1.5-1.8B-Chat,10,cpu,11.990,7006.9,259.7,477.8,262.751,1000,3.81,100.0,26.275