In [9]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [10]:
result_tinyllama = pd.read_csv('../results/metrics/tinyllama/se_auroc_summary.csv')
result_tinyllama

,model,dataset,language,n_questions,M,temperature,auroc,aurac,best_threshold,accuracy,wrete_macro_f1,avg_entropy,std_entropy,total_time_s,similarity_calls_total,avg_latency_s,throughput_tok_s,peak_ram_mb,f1_threshold,max_tokens,load_time_s,model_size_mb,ram_after_load_mb,ram_available_mb
0,TinyLlama/TinyLlama-1.1B-Chat-v1.0,trivia_qa,en,100,10,0.5,0.7807,0.2502,NaN,0.24,NaN,0.7632,0.6333,20363.8,4500,203.64,1.73,2731.1,0.5,30,4.412,2098.2,2529.5,2407.5
1,TinyLlama/TinyLlama-1.1B-Chat-v1.0,bioasq,en,100,10,0.5,0.5971,0.0535,NaN,0.08,NaN,0.4742,0.5701,23293.3,4500,232.93,1.35,3172.4,0.5,30,5.954,2098.2,3172.4,2750.3
2,TinyLlama/TinyLlama-1.1B-Chat-v1.0,facqa,id,100,10,0.5,0.5434,0.1765,NaN,0.22,NaN,0.5576,0.4528,18570.8,4500,185.71,1.75,2980.0,0.5,30,4.438,2098.2,1876.1,1557.3
3,TinyLlama/TinyLlama-1.1B-Chat-v1.0,wrete,id,100,10,0.5,0.4130,0.1300,NaN,0.23,0.3343,0.4014,0.3742,30331.6,4500,303.32,1.13,2117.2,0.5,30,7.841,2098.2,870.9,2173.3

In [11]:
result_phi = pd.read_csv('../results/metrics/phi/se_auroc_summary.csv')
result_phi2 = pd.read_csv('../results/metrics/phi/se_auroc_summary(2).csv')
result_phi

,model,dataset,language,n_questions,M,temperature,auroc,aurac,best_threshold,accuracy,wrete_macro_f1,avg_entropy,std_entropy,total_time_s,similarity_calls_total,avg_latency_s,throughput_tok_s,peak_ram_mb,f1_threshold,max_tokens,load_time_s,model_size_mb,ram_after_load_mb,ram_available_mb
0,microsoft/phi-1_5,trivia_qa,en,100,10,0.5,0.7235,0.1467,NaN,0.08,NaN,1.7729,0.4617,29504.7,4500,295.05,1.13,1447.2,0.5,30,2.218,2705.1,751.2,1348.9
1,microsoft/phi-1_5,bioasq,en,100,10,0.5,0.5247,0.0372,NaN,0.04,NaN,0.9141,0.6330,15536.1,4500,155.36,2.24,3246.7,0.5,30,1.617,2705.1,1413.6,2526.0

In [12]:
result_phi2

,model,dataset,language,n_questions,M,temperature,auroc,aurac,best_threshold,accuracy,wrete_macro_f1,avg_entropy,std_entropy,total_time_s,similarity_calls_total,avg_latency_s,throughput_tok_s,peak_ram_mb,f1_threshold,max_tokens,load_time_s,model_size_mb,ram_after_load_mb,ram_available_mb
0,microsoft/phi-1_5,facqa,id,100,10,0.5,0.6375,0.0331,NaN,0.03,NaN,0.5268,0.4080,13843.5,4500,138.44,2.45,3438.9,0.5,30,1.904,2705.1,753.7,3190.3
1,microsoft/phi-1_5,wrete,id,100,10,0.5,0.5000,0.1396,NaN,0.15,0.2084,1.0593,0.5199,13429.0,4500,134.29,2.54,3463.8,0.5,30,1.526,2705.1,907.6,4926.1

In [13]:
result_qwen = pd.read_csv('../results/metrics/qwen/se_auroc_summary.csv')
result_qwen

,model,dataset,language,n_questions,M,temperature,auroc,aurac,best_threshold,accuracy,wrete_macro_f1,avg_entropy,std_entropy,total_time_s,similarity_calls_total,avg_latency_s,throughput_tok_s,peak_ram_mb,f1_threshold,max_tokens,load_time_s,model_size_mb,ram_after_load_mb,ram_available_mb
0,Qwen/Qwen1.5-1.8B-Chat,trivia_qa,en,100,10,0.5,0.8546,0.1912,NaN,0.13,NaN,1.0358,0.6995,23812.3,4500,238.12,0.52,2640.3,0.5,30,8.469,3503.5,1943.0,3260.1
1,Qwen/Qwen1.5-1.8B-Chat,bioasq,en,100,10,0.5,0.4260,0.0142,NaN,0.02,NaN,0.9911,0.5559,9419.8,4500,94.20,2.25,5040.3,0.5,30,4.750,3503.5,5021.2,3804.1
2,Qwen/Qwen1.5-1.8B-Chat,facqa,id,100,10,0.5,0.6072,0.2578,NaN,0.49,NaN,0.3379,0.4257,19637.2,4500,196.37,1.33,4344.9,0.5,30,6.664,3503.5,4210.4,3679.1
3,Qwen/Qwen1.5-1.8B-Chat,wrete,id,100,10,0.5,0.5023,0.5964,1.2675,0.68,0.6736,0.8896,0.3911,26323.2,4500,263.23,1.09,3619.5,0.5,30,6.073,3503.5,2771.7,3761.5